#Dados dos números, mostrar la suma, resta, división y multiplicación de ambos
print("========================")
print("\tEJERCICIO 03")
print("========================")
print("Operaciones con 2 números\n")
num_a = float(input("Ingrese el numero a: \n"))
num_b = float(input("Ingrese el numero b: \n"))
print("La SUMA es: ", round(num_a + num_b,2))
print("La RESTA es: ", round(num_a - num_b,2))
print("El PRODUCTO es: ", round(num_a * num_b,2))
